// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwvPJ0s1IdpFNH04NhNj6Rkq_zlTQFWHo',
    appId: '1:567691117582:web:f6d9bc0e8572dca70de85f',
    messagingSenderId: '567691117582',
    projectId: 'quiz-94796',
    authDomain: 'quiz-94796.firebaseapp.com',
    storageBucket: 'quiz-94796.firebasestorage.app',
    measurementId: 'G-8YQ5JN6Z8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF5ePbX7n7DJH4ZUTe8LzA3JBlPkXDfaw',
    appId: '1:567691117582:android:27d737ed17a10ded0de85f',
    messagingSenderId: '567691117582',
    projectId: 'quiz-94796',
    storageBucket: 'quiz-94796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSBHNjTeA5NJQJvRS5K_cX48DdWOttsUE',
    appId: '1:567691117582:ios:4ec4144ac4a7fa310de85f',
    messagingSenderId: '567691117582',
    projectId: 'quiz-94796',
    storageBucket: 'quiz-94796.firebasestorage.app',
    iosBundleId: 'com.devarch.qways',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSBHNjTeA5NJQJvRS5K_cX48DdWOttsUE',
    appId: '1:567691117582:ios:ddbd1f7f714ac3840de85f',
    messagingSenderId: '567691117582',
    projectId: 'quiz-94796',
    storageBucket: 'quiz-94796.firebasestorage.app',
    iosBundleId: 'com.devarch.qways',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwvPJ0s1IdpFNH04NhNj6Rkq_zlTQFWHo',
    appId: '1:567691117582:web:22fe35d945c995350de85f',
    messagingSenderId: '567691117582',
    projectId: 'quiz-94796',
    authDomain: 'quiz-94796.firebaseapp.com',
    storageBucket: 'quiz-94796.firebasestorage.app',
    measurementId: 'G-M2CGHNL79N',
  );
}